global:
    scrape_interval: 5s
    external_labels:
        monitor: 'lambda-monitor'
scrape_configs:
    - job_name: 'docker'
      target_groups:
          - targets: ['host.docker.internal:9841']
    - job_name: 'eexporter'
      target_groups:
          - targets: ['host.docker.internal:9114']
